[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''

[[plugins]]
repo        = 'roxma/nvim-yarp'
on_event    = 'InsertEnter'

[[plugins]]
repo        = 'roxma/vim-hug-neovim-rpc'
on_event    = 'InsertEnter'

[[plugins]]
repo        = 'Shougo/neco-syntax'
on_event    = 'InsertEnter'

[[plugins]]
repo        = 'ujihisa/neco-look'
on_event    = 'InsertEnter'

[[plugins]]
repo        = 'wokalski/autocomplete-flow'
on_event    = 'InsertEnter'

[[plugins]]
repo        = 'plasticboy/vim-markdown'
on_ft       = ['markdown']

[[plugins]]
repo        = 'davidhalter/jedi-vim'
on_ft       = ['python']

[[plugins]]
repo        = 'zchee/deoplete-jedi'
on_ft       = ['python']

[[plugins]]
repo        = 'othree/html5.vim'
on_ft       = ['html', 'erb']

[[plugins]]
repo        = 'alvan/vim-closetag'
on_ft       = ['html', 'erb']

[[plugins]]
repo        = 'hail2u/vim-css3-syntax'
on_ft       = ['css']

[[plugins]]
repo        = 'pangloss/vim-javascript'
on_ft       = ['javascript']

[[plugins]]
repo        = 'carlitux/deoplete-ternjs'
on_ft       = ['javascript']

[[plugins]]
repo        = 'vim-scripts/java.vim'
on_ft       = ['java']

[[plugins]]
repo        = 'artur-shaik/vim-javacomplete2'
on_ft       = ['java']

[[plugins]]
repo        = 'rust-lang/rust.vim'
on_ft       = ['rust']

[[plugins]]
repo        = 'racer-rust/vim-racer'
on_ft       = ['rust']

[[plugins]]
repo        = 'sebastianmarkow/deoplete-rust'
on_ft       = ['rust']

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

# end complete for ruby
#[[plugins]]
#repo = 'tpope/vim-endwise'
#on_i = 1
#on_ft = ['ruby']

# Jump definition
[[plugins]]
repo = 'szw/vim-tags'
