#!/bin/bash
# c++_installerは、C++関連ライブラリをインストールする。
#
# Copyright (c) 2020 Naohiro CHIKAMATSU (Nao1215)
# This software is released under the MIT License, see LICENSE.

# ライブラリインポート
source libinstaller

# グローバル変数
C_PLUSPLUS_TOOLS="gcc g++ build-essential libboost-all-dev clang qtcreator gcc-8 g++-8 make"

# メイン処理部
isRoot
aptInstall "${C_PLUSPLUS_TOOLS}"