#!/bin/bash
# fish_installerは、fish shellとfisher(プラグインマネージャ)をインストールする。
#
# Copyright (c) 2020 Naohiro CHIKAMATSU (Nao1215)
# This software is released under the MIT License, see LICENSE.

# ライブラリインポート
source libinstaller

# グローバル変数
FISH_PKG="fish"

# installFisher()は、fisherプラグインマネージャをインストールする。
function installFisher() {
    echo "Fisherプラグインマネージャをインストールします。"
    curl https://git.io/fisher --create-dirs -sLo ${HOME_DIR}/.config/fish/functions/fisher.fish
    chown -R ${USER_NAME}:${USER_NAME} ${HOME_DIR}/.config/fish/functions/fisher.fish
}

# installFishConfigFile()は、fishの設定ファイルをインストールする。
function installFishConfigFile() {
    echo "Fishの設定ファイルをインストールします。"
    sudo -u ${USER_NAME} cp -f fish/config.fish ${HOME_DIR}/.config/fish/.
    sudo -u ${USER_NAME} cp -f fish/fish_variables ${HOME_DIR}/.config/fish/.
}

# installFishPlugin()は、fishプラグインをインストールする。
function installFishPlugin() {
    echo "Fisherプラグインマネージャでfishプラグインをインストールします。"
    sudo -u ${USER_NAME} ./fisher_installer
}

# changeLoginShellToFish()は、ログインシェルをfishに変更する。
function changeLoginShellToFish()  {
    echo "ログインシェルをfishに変更します。"
    local fish_path=$(cat /etc/shells | grep fish)
    sudo -u ${USER_NAME} chsh --shell ${fish_path} ${USER_NAME}
}

# メイン処理部
isRoot
aptInstall ${FISH_PKG}
installFishPlugin
installFishConfigFile
changeLoginShellToFish
