#!/bin/bash
# python3_installerは、python3および関連ライブラリをインストールする。
#
# Copyright (c) 2020 Naohiro CHIKAMATSU (Nao1215)
# This software is released under the MIT License, see LICENSE.

# ライブラリインポート
source libinstaller

# グローバル変数
PYTHON_TOOLS="python3 python3-dev python3-pip"
PYTHON_LIBS="jedi urllib3 beautifulsoup4 lxml pep8i tqdm requests"

# メイン処理部
isRoot
aptInstall "${PYTHON_TOOLS}"
pip3Install "${PYTHON_LIBS}"
